name: mysql5_client
description: mysql5.x driver
version: 0.3.0
authors:
  - Roberto Tassi
  - WangLiQi <1010993610@qq.com>
repository: "https://github.com/Silentdoer/mysql5_client.git"

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: "^3.0.0"
  pool: "^1.5.0"
dev_dependencies:
  stack_trace: "^1.10.0"
  test: '>=1.16.8 <2.0.0'
