name: mysql5_client
description: mysql5.x driver
version: 0.2.0
authors:
  - Roberto Tassi
  - WangLiQi <1010993610@qq.com>
repository: "https://github.com/Silentdoer/mysql5_client.git"

environment:
  sdk: '>=2.10.1 <3.0.0'

dependencies:
  crypto: "^2.1.5"
  pool: "^1.4.0"
dev_dependencies:
  stack_trace: "^1.9.6"
  test: '>=1.15.5 <2.0.0'
