name: mysql5_client
description: A starting point for Dart libraries or applications.
version: 0.1.0
author: ["Roberto Tassi", "silentdoer"]

environment:
  sdk: '>=2.10.1 <3.0.0'

dependencies:
  crypto: "^2.1.5"
  convert: "^2.1.1"
  pool: "^1.4.0"
dev_dependencies:
  stack_trace: "^1.9.6"
  test: '>=1.15.5 <2.0.0'
